"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['App.py']
DATA_FILES = ["Spaceship.bmp"]
OPTIONS = {}

setup(
    app=APP,
    #py_modules=["Heavenly_Bodies.py"],
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
